language: python
sudo: false
python:
  - "3.6"

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install --upgrade pycodestyle pyflakes coverage python-coveralls pytest pytest-cov
  - python setup.py develop

script:
  - pycodestyle .
  - pyflakes .
  - py.test --cov=formica tests/

after_success:
  - coveralls