stack: formica-test-stack
# role-arn: arn:aws:iam::080551076419:role/test/1/formica-test-stack-2-TestRole1-1PGVZJ88QDVBD
capabilities:
  - CAPABILITY_IAM
vars:
  buckets:
    - 1
    - 2
  PolicyName: TestRolePolicy