Resources:
  S3TestBucket:
    Type: AWS::S3::Bucket

  S3TestBucket2:
    Type: AWS::S3::Bucket

  TestRole1:
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /test/1/
      Policies:
      - PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action: "*"
              Resource: "*"
        PolicyName: TestRole1
    Type: AWS::IAM::Role